version: '3.8'
services:
  mariadb:
    image: mariadb:latest
    container_name: my_mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  mariadb_data:

networks:
  mynetwork:
